name: CI - Build, Test, Docker Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy

      - name: Cache cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --all

      - name: Clippy (Lint)
        run: cargo clippy --all -- -D warnings

      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main' && matrix.rust == 'stable'
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up QEMU
        if: github.ref == 'refs/heads/main' && matrix.rust == 'stable'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main' && matrix.rust == 'stable'
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main' && matrix.rust == 'stable'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
